---
_format_version: '3.0'
_transform: true
services:
- name: service-v1
  url: http://www.mocky.io
  routes:
  - name: route-v1
    paths:
    - "/route-1"
    methods:
    - GET
  plugins:
  - name: rate-limiting
    config:
      policy: local
      limit_by: ip
      minute: 3
  - name: key-auth
  - name: basic-auth
  - name: jwt
    enabled: true
    service: service-v1
    config:
      header_names:
      - Authorization
      key_claim_name: kid
      claims_to_verify:
      - exp
  - name: response-transformer
    service: service-v1
    route: route-v1
    config:
      add:
        json:
        - p1:v1
        - p2=v2
        headers:
        - h1:v1
consumers:
- custom_id: "{{$guid}}"
  keyauth_credentials:
  - key: mykey123
- custom_id: "{{$guid}}"
  basicauth_credentials:
  - username: seshu
    password: seshu123
- username: login_server_issuer
  jwt_secrets:
  - consumer: login_server_issuer
    algorithm: HS256
    secret: Hey-Hi-Its-My-Secret
