# apiVersion: configuration.konghq.com/v1
# kind: KongClusterPlugin
# metadata:
#   name: prometheus
#   annotations:
#     kubernetes.io/ingress.class: kong
#   labels:
#     global: "true"
# config:
#   per_consumer: false
# plugin: prometheus
# ---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus
plugin: prometheus
config:
  per_consumer: false