---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: companytwo
credentials:
  - companytwo-basic-auth
username: companytwo