apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: loki-stack
spec:
project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.8.8
    helm:
      valueFiles:
        - values.yaml
    chart: loki-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true