{
 "title": "Kong Gateway API Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Hello World API Success Response - 200",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"kong\"} |~ `\"GET /my-service-three/kong-demo-api HTTP/2.0\" 200`"
    }
   ]
  },
  {
   "title": "Hello World API Status Code 429",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"kong\"} |~ `\"GET /my-service-three/kong-demo-api HTTP/2.0\" 429`"
    }
   ]
  },
  {
   "title": "200 OK Count for Hello World API",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({namespace=\"kong\"} |~ `\"GET /my-service-three/kong-demo-api HTTP/2.0\" 200` [$__range]))"
    }
   ]
  },
  {
   "title": "429 Too many requests error for Hello World API",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({container=\"proxy\"} |~ `GET /my-service-three/kong-demo-api HTTP/2.0\" 429` [$__range]))"
    }
   ]
  }
 ]
}