---    
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: response-transformer-example
plugin: response-transformer
config:
  add:
    json:
    - new-json-key:some_value
    - another-json-key:some_value