---  
apiVersion: apps/v1
kind: Deployment
metadata:
     labels:
       app: node-helloworld-service-app
     name: node-helloworld-deployment
     namespace: default
spec:
     replicas: 1
     selector:
       matchLabels:
         app: node-helloworld-service-app
     template:
       metadata:
         labels:
           app: node-helloworld-service-app
       spec:
         containers:
         - image: gcr.io/google-samples/node-hello:1.0
           name: hello-world
           ports:
           - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-helloworld-service-app
  name: node-helloworld-service
  annotations:
    konghq.com/plugins: node-helloworld-service-rate-limiting
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: node-helloworld-service-app 