apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sandbox-kong-selfsigned-issuer-root
  namespace: kong
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sandbox-kong-selfsigned-issuer-ca
  namespace: kong
spec:
  commonName: sandbox-kong-selfsigned-issuer-ca
  duration: 2160h0m0s
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: sandbox-kong-selfsigned-issuer-root
    namespace: kong
  privateKey:
    algorithm: ECDSA
    size: 256
  renewBefore: 360h0m0s
  secretName: sandbox-kong-selfsigned-issuer-ca
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sandbox-kong-selfsigned-issuer
  namespace: kong
spec:
  ca:
    secretName: sandbox-kong-selfsigned-issuer-ca